# Auto-generated list of SuperTux sources for ndk-build.
# Regenerate: find src -name "*.cpp" | sort > mk/android/app/jni/supertux_sources.list
SUPERTUX_SOURCES := \
  ../../../../src/audio/sound_manager.cpp \
  ../../../../src/audio/sound_source.cpp \
  ../../../../src/badguy/angrystone.cpp \
  ../../../../src/badguy/badguy.cpp \
  ../../../../src/badguy/bomb.cpp \
  ../../../../src/badguy/bouncing_snowball.cpp \
  ../../../../src/badguy/captainsnowball.cpp \
  ../../../../src/badguy/crusher.cpp \
  ../../../../src/badguy/crystallo.cpp \
  ../../../../src/badguy/dart.cpp \
  ../../../../src/badguy/darttrap.cpp \
  ../../../../src/badguy/dispenser.cpp \
  ../../../../src/badguy/fish_chasing.cpp \
  ../../../../src/badguy/fish_harmless.cpp \
  ../../../../src/badguy/fish_jumping.cpp \
  ../../../../src/badguy/fish_swimming.cpp \
  ../../../../src/badguy/flame.cpp \
  ../../../../src/badguy/flyingsnowball.cpp \
  ../../../../src/badguy/ghostflame.cpp \
  ../../../../src/badguy/ghosttree.cpp \
  ../../../../src/badguy/ghoul.cpp \
  ../../../../src/badguy/goldbomb.cpp \
  ../../../../src/badguy/haywire.cpp \
  ../../../../src/badguy/iceflame.cpp \
  ../../../../src/badguy/igel.cpp \
  ../../../../src/badguy/jumpy.cpp \
  ../../../../src/badguy/kamikazesnowball.cpp \
  ../../../../src/badguy/kugelblitz.cpp \
  ../../../../src/badguy/livefire.cpp \
  ../../../../src/badguy/mole.cpp \
  ../../../../src/badguy/mole_rock.cpp \
  ../../../../src/badguy/mrbomb.cpp \
  ../../../../src/badguy/mriceblock.cpp \
  ../../../../src/badguy/mrtree.cpp \
  ../../../../src/badguy/owl.cpp \
  ../../../../src/badguy/plant.cpp \
  ../../../../src/badguy/rcrystallo.cpp \
  ../../../../src/badguy/root.cpp \
  ../../../../src/badguy/scrystallo.cpp \
  ../../../../src/badguy/short_fuse.cpp \
  ../../../../src/badguy/skullyhop.cpp \
  ../../../../src/badguy/skydive.cpp \
  ../../../../src/badguy/smartball.cpp \
  ../../../../src/badguy/smartblock.cpp \
  ../../../../src/badguy/snail.cpp \
  ../../../../src/badguy/snowball.cpp \
  ../../../../src/badguy/snowman.cpp \
  ../../../../src/badguy/spidermite.cpp \
  ../../../../src/badguy/spiky.cpp \
  ../../../../src/badguy/sspiky.cpp \
  ../../../../src/badguy/stalactite.cpp \
  ../../../../src/badguy/stumpy.cpp \
  ../../../../src/badguy/toad.cpp \
  ../../../../src/badguy/totem.cpp \
  ../../../../src/badguy/treewillowisp.cpp \
  ../../../../src/badguy/viciousivy.cpp \
  ../../../../src/badguy/walking_badguy.cpp \
  ../../../../src/badguy/walking_candle.cpp \
  ../../../../src/badguy/walkingleaf.cpp \
  ../../../../src/badguy/willowisp.cpp \
  ../../../../src/badguy/yeti.cpp \
  ../../../../src/badguy/yeti_stalactite.cpp \
  ../../../../src/badguy/zeekling.cpp \
  ../../../../src/collision/collision.cpp \
  ../../../../src/collision/collision_movement_manager.cpp \
  ../../../../src/collision/collision_object.cpp \
  ../../../../src/collision/collision_system.cpp \
  ../../../../src/control/codecontroller.cpp \
  ../../../../src/control/controller.cpp \
  ../../../../src/control/game_controller_manager.cpp \
  ../../../../src/control/input_manager.cpp \
  ../../../../src/control/joystick_config.cpp \
  ../../../../src/control/joystick_manager.cpp \
  ../../../../src/control/keyboard_config.cpp \
  ../../../../src/control/keyboard_manager.cpp \
  ../../../../src/control/mobile_controller.cpp \
  ../../../../src/gui/dialog.cpp \
  ../../../../src/gui/item_action.cpp \
  ../../../../src/gui/item_back.cpp \
  ../../../../src/gui/item_controlfield.cpp \
  ../../../../src/gui/item_goto.cpp \
  ../../../../src/gui/item_hl.cpp \
  ../../../../src/gui/item_inactive.cpp \
  ../../../../src/gui/item_label.cpp \
  ../../../../src/gui/item_stringselect.cpp \
  ../../../../src/gui/item_toggle.cpp \
  ../../../../src/gui/menu.cpp \
  ../../../../src/gui/menu_filesystem.cpp \
  ../../../../src/gui/menu_item.cpp \
  ../../../../src/gui/menu_list.cpp \
  ../../../../src/gui/menu_manager.cpp \
  ../../../../src/gui/mousecursor.cpp \
  ../../../../src/gui/notification.cpp \
  ../../../../src/main.cpp \
  ../../../../src/math/aatriangle.cpp \
  ../../../../src/math/anchor_point.cpp \
  ../../../../src/math/bezier.cpp \
  ../../../../src/math/easing.cpp \
  ../../../../src/math/random.cpp \
  ../../../../src/math/rect.cpp \
  ../../../../src/math/rectf.cpp \
  ../../../../src/math/size.cpp \
  ../../../../src/math/sizef.cpp \
  ../../../../src/object/ambient_light.cpp \
  ../../../../src/object/ambient_sound.cpp \
  ../../../../src/object/background.cpp \
  ../../../../src/object/bicycle_platform.cpp \
  ../../../../src/object/block.cpp \
  ../../../../src/object/bonus_block.cpp \
  ../../../../src/object/bouncy_coin.cpp \
  ../../../../src/object/brick.cpp \
  ../../../../src/object/bullet.cpp \
  ../../../../src/object/bumper.cpp \
  ../../../../src/object/camera.cpp \
  ../../../../src/object/candle.cpp \
  ../../../../src/object/circleplatform.cpp \
  ../../../../src/object/cloud_particle_system.cpp \
  ../../../../src/object/coin.cpp \
  ../../../../src/object/coin_explode.cpp \
  ../../../../src/object/coin_rain.cpp \
  ../../../../src/object/custom_particle_system.cpp \
  ../../../../src/object/custom_particle_system_file.cpp \
  ../../../../src/object/decal.cpp \
  ../../../../src/object/display_effect.cpp \
  ../../../../src/object/electrifier.cpp \
  ../../../../src/object/endsequence.cpp \
  ../../../../src/object/endsequence_fireworks.cpp \
  ../../../../src/object/endsequence_walk.cpp \
  ../../../../src/object/explosion.cpp \
  ../../../../src/object/fallblock.cpp \
  ../../../../src/object/falling_coin.cpp \
  ../../../../src/object/firefly.cpp \
  ../../../../src/object/fireworks.cpp \
  ../../../../src/object/floating_image.cpp \
  ../../../../src/object/floating_text.cpp \
  ../../../../src/object/flower.cpp \
  ../../../../src/object/ghost_particle_system.cpp \
  ../../../../src/object/gradient.cpp \
  ../../../../src/object/growup.cpp \
  ../../../../src/object/hurting_platform.cpp \
  ../../../../src/object/infoblock.cpp \
  ../../../../src/object/invisible_block.cpp \
  ../../../../src/object/invisible_wall.cpp \
  ../../../../src/object/ispy.cpp \
  ../../../../src/object/lantern.cpp \
  ../../../../src/object/level_time.cpp \
  ../../../../src/object/light.cpp \
  ../../../../src/object/lit_object.cpp \
  ../../../../src/object/magicblock.cpp \
  ../../../../src/object/moving_sprite.cpp \
  ../../../../src/object/music_object.cpp \
  ../../../../src/object/oneup.cpp \
  ../../../../src/object/particle_zone.cpp \
  ../../../../src/object/particles.cpp \
  ../../../../src/object/particlesystem.cpp \
  ../../../../src/object/particlesystem_interactive.cpp \
  ../../../../src/object/path.cpp \
  ../../../../src/object/path_gameobject.cpp \
  ../../../../src/object/path_object.cpp \
  ../../../../src/object/path_walker.cpp \
  ../../../../src/object/platform.cpp \
  ../../../../src/object/player.cpp \
  ../../../../src/object/pneumatic_platform.cpp \
  ../../../../src/object/powerup.cpp \
  ../../../../src/object/pulsing_light.cpp \
  ../../../../src/object/pushbutton.cpp \
  ../../../../src/object/rain_particle_system.cpp \
  ../../../../src/object/rainsplash.cpp \
  ../../../../src/object/rock.cpp \
  ../../../../src/object/rublight.cpp \
  ../../../../src/object/rusty_trampoline.cpp \
  ../../../../src/object/scripted_object.cpp \
  ../../../../src/object/shard.cpp \
  ../../../../src/object/skull_tile.cpp \
  ../../../../src/object/smoke_cloud.cpp \
  ../../../../src/object/snow_particle_system.cpp \
  ../../../../src/object/spawnpoint.cpp \
  ../../../../src/object/specialriser.cpp \
  ../../../../src/object/spotlight.cpp \
  ../../../../src/object/sprite_particle.cpp \
  ../../../../src/object/star.cpp \
  ../../../../src/object/text_array_object.cpp \
  ../../../../src/object/text_object.cpp \
  ../../../../src/object/textscroller.cpp \
  ../../../../src/object/thunderstorm.cpp \
  ../../../../src/object/tilemap.cpp \
  ../../../../src/object/torch.cpp \
  ../../../../src/object/trampoline.cpp \
  ../../../../src/object/unstable_tile.cpp \
  ../../../../src/object/vertical_stripes.cpp \
  ../../../../src/object/water_drop.cpp \
  ../../../../src/object/weak_block.cpp \
  ../../../../src/object/wind.cpp \
  ../../../../src/physfs/ifile_stream.cpp \
  ../../../../src/physfs/ifile_streambuf.cpp \
  ../../../../src/physfs/ofile_stream.cpp \
  ../../../../src/physfs/ofile_streambuf.cpp \
  ../../../../src/physfs/physfs_sdl.cpp \
  ../../../../src/physfs/util.cpp \
  ../../../../src/scripting/ambient_sound.cpp \
  ../../../../src/scripting/background.cpp \
  ../../../../src/scripting/badguy.cpp \
  ../../../../src/scripting/camera.cpp \
  ../../../../src/scripting/candle.cpp \
  ../../../../src/scripting/clouds.cpp \
  ../../../../src/scripting/custom_particles.cpp \
  ../../../../src/scripting/decal.cpp \
  ../../../../src/scripting/dispenser.cpp \
  ../../../../src/scripting/display_effect.cpp \
  ../../../../src/scripting/floating_image.cpp \
  ../../../../src/scripting/functions.cpp \
  ../../../../src/scripting/game_object.cpp \
  ../../../../src/scripting/game_object_manager.cpp \
  ../../../../src/scripting/gradient.cpp \
  ../../../../src/scripting/level.cpp \
  ../../../../src/scripting/level_time.cpp \
  ../../../../src/scripting/lit_object.cpp \
  ../../../../src/scripting/particlesystem.cpp \
  ../../../../src/scripting/platform.cpp \
  ../../../../src/scripting/player.cpp \
  ../../../../src/scripting/rain.cpp \
  ../../../../src/scripting/scripted_object.cpp \
  ../../../../src/scripting/sector.cpp \
  ../../../../src/scripting/spotlight.cpp \
  ../../../../src/scripting/text.cpp \
  ../../../../src/scripting/text_array.cpp \
  ../../../../src/scripting/thunderstorm.cpp \
  ../../../../src/scripting/tilemap.cpp \
  ../../../../src/scripting/torch.cpp \
  ../../../../src/scripting/willowisp.cpp \
  ../../../../src/scripting/wind.cpp \
  ../../../../src/scripting/worldmap.cpp \
  ../../../../src/scripting/wrapper.cpp \
  ../../../../src/sprite/sprite.cpp \
  ../../../../src/sprite/sprite_data.cpp \
  ../../../../src/sprite/sprite_manager.cpp \
  ../../../../src/squirrel/serialize.cpp \
  ../../../../src/squirrel/squirrel_environment.cpp \
  ../../../../src/squirrel/squirrel_error.cpp \
  ../../../../src/squirrel/squirrel_scheduler.cpp \
  ../../../../src/squirrel/squirrel_thread_queue.cpp \
  ../../../../src/squirrel/squirrel_util.cpp \
  ../../../../src/squirrel/squirrel_virtual_machine.cpp \
  ../../../../src/squirrel/squirrel_vm.cpp \
  ../../../../src/supertux/colorscheme.cpp \
  ../../../../src/supertux/command_line_arguments.cpp \
  ../../../../src/supertux/console.cpp \
  ../../../../src/supertux/controller_hud.cpp \
  ../../../../src/supertux/d_scope.cpp \
  ../../../../src/supertux/debug.cpp \
  ../../../../src/supertux/direction.cpp \
  ../../../../src/supertux/error_handler.cpp \
  ../../../../src/supertux/fadetoblack.cpp \
  ../../../../src/supertux/game_manager.cpp \
  ../../../../src/supertux/game_object.cpp \
  ../../../../src/supertux/game_object_factory.cpp \
  ../../../../src/supertux/game_object_iterator.cpp \
  ../../../../src/supertux/game_object_manager.cpp \
  ../../../../src/supertux/game_session.cpp \
  ../../../../src/supertux/game_session_recorder.cpp \
  ../../../../src/supertux/gameconfig.cpp \
  ../../../../src/supertux/globals.cpp \
  ../../../../src/supertux/info_box.cpp \
  ../../../../src/supertux/info_box_line.cpp \
  ../../../../src/supertux/level.cpp \
  ../../../../src/supertux/level_parser.cpp \
  ../../../../src/supertux/level_transformer.cpp \
  ../../../../src/supertux/levelintro.cpp \
  ../../../../src/supertux/levelset.cpp \
  ../../../../src/supertux/levelset_screen.cpp \
  ../../../../src/supertux/main.cpp \
  ../../../../src/supertux/menu/cheat_menu.cpp \
  ../../../../src/supertux/menu/contrib_levelset_menu.cpp \
  ../../../../src/supertux/menu/debug_menu.cpp \
  ../../../../src/supertux/menu/game_menu.cpp \
  ../../../../src/supertux/menu/joystick_menu.cpp \
  ../../../../src/supertux/menu/keyboard_menu.cpp \
  ../../../../src/supertux/menu/main_menu.cpp \
  ../../../../src/supertux/menu/menu_storage.cpp \
  ../../../../src/supertux/menu/multiplayer_menu.cpp \
  ../../../../src/supertux/menu/multiplayer_player_menu.cpp \
  ../../../../src/supertux/menu/multiplayer_players_menu.cpp \
  ../../../../src/supertux/menu/options_menu.cpp \
  ../../../../src/supertux/menu/sorted_contrib_menu.cpp \
  ../../../../src/supertux/menu/worldmap_cheat_apply_menu.cpp \
  ../../../../src/supertux/menu/worldmap_cheat_menu.cpp \
  ../../../../src/supertux/menu/worldmap_menu.cpp \
  ../../../../src/supertux/moving_object.cpp \
  ../../../../src/supertux/object_factory.cpp \
  ../../../../src/supertux/physic.cpp \
  ../../../../src/supertux/player_status.cpp \
  ../../../../src/supertux/player_status_hud.cpp \
  ../../../../src/supertux/resources.cpp \
  ../../../../src/supertux/savegame.cpp \
  ../../../../src/supertux/screen_manager.cpp \
  ../../../../src/supertux/sector.cpp \
  ../../../../src/supertux/sector_parser.cpp \
  ../../../../src/supertux/sequence.cpp \
  ../../../../src/supertux/shrinkfade.cpp \
  ../../../../src/supertux/statistics.cpp \
  ../../../../src/supertux/textscroller_screen.cpp \
  ../../../../src/supertux/tile.cpp \
  ../../../../src/supertux/tile_manager.cpp \
  ../../../../src/supertux/tile_set.cpp \
  ../../../../src/supertux/tile_set_parser.cpp \
  ../../../../src/supertux/timer.cpp \
  ../../../../src/supertux/title_screen.cpp \
  ../../../../src/supertux/world.cpp \
  ../../../../src/trigger/climbable.cpp \
  ../../../../src/trigger/door.cpp \
  ../../../../src/trigger/scripttrigger.cpp \
  ../../../../src/trigger/secretarea_trigger.cpp \
  ../../../../src/trigger/sequence_trigger.cpp \
  ../../../../src/trigger/switch.cpp \
  ../../../../src/trigger/text_area.cpp \
  ../../../../src/trigger/trigger_base.cpp \
  ../../../../src/util/colorspace_oklab.cpp \
  ../../../../src/util/fade_helper.cpp \
  ../../../../src/util/file_system.cpp \
  ../../../../src/util/gettext.cpp \
  ../../../../src/util/line_iterator.cpp \
  ../../../../src/util/log.cpp \
  ../../../../src/util/reader.cpp \
  ../../../../src/util/reader_iterator.cpp \
  ../../../../src/util/timelog.cpp \
  ../../../../src/util/uid.cpp \
  ../../../../src/util/uid_generator.cpp \
  ../../../../src/util/unique_name.cpp \
  ../../../../src/util/utf8_iterator.cpp \
  ../../../../src/util/writer.cpp \
  ../../../../src/video/bitmap_font.cpp \
  ../../../../src/video/blend.cpp \
  ../../../../src/video/canvas.cpp \
  ../../../../src/video/color.cpp \
  ../../../../src/video/compositor.cpp \
  ../../../../src/video/drawing_context.cpp \
  ../../../../src/video/drawing_target.cpp \
  ../../../../src/video/font.cpp \
  ../../../../src/video/gl/gl33core_context.cpp \
  ../../../../src/video/gl/gl_framebuffer.cpp \
  ../../../../src/video/gl/gl_painter.cpp \
  ../../../../src/video/gl/gl_program.cpp \
  ../../../../src/video/gl/gl_screen_renderer.cpp \
  ../../../../src/video/gl/gl_shader.cpp \
  ../../../../src/video/gl/gl_texture.cpp \
  ../../../../src/video/gl/gl_texture_renderer.cpp \
  ../../../../src/video/gl/gl_vertex_arrays.cpp \
  ../../../../src/video/gl/gl_video_system.cpp \
  ../../../../src/video/null/null_painter.cpp \
  ../../../../src/video/null/null_renderer.cpp \
  ../../../../src/video/null/null_texture.cpp \
  ../../../../src/video/null/null_video_system.cpp \
  ../../../../src/video/sampler.cpp \
  ../../../../src/video/sdl_surface.cpp \
  ../../../../src/video/sdlbase_video_system.cpp \
  ../../../../src/video/surface.cpp \
  ../../../../src/video/surface_batch.cpp \
  ../../../../src/video/texture.cpp \
  ../../../../src/video/texture_manager.cpp \
  ../../../../src/video/ttf_font.cpp \
  ../../../../src/video/ttf_surface.cpp \
  ../../../../src/video/ttf_surface_manager.cpp \
  ../../../../src/video/video_system.cpp \
  ../../../../src/video/viewport.cpp \
  ../../../../src/worldmap/camera.cpp \
  ../../../../src/worldmap/direction.cpp \
  ../../../../src/worldmap/level_tile.cpp \
  ../../../../src/worldmap/spawn_point.cpp \
  ../../../../src/worldmap/special_tile.cpp \
  ../../../../src/worldmap/sprite_change.cpp \
  ../../../../src/worldmap/teleporter.cpp \
  ../../../../src/worldmap/tux.cpp \
  ../../../../src/worldmap/worldmap.cpp \
  ../../../../src/worldmap/worldmap_parser.cpp \
  ../../../../src/worldmap/worldmap_screen.cpp \
  ../../../../src/worldmap/worldmap_state.cpp \
  placeholder.cpp
